const fs = require('fs')
let code = fs.readFileSync('frontend/src/App.tsx', 'utf-8')
code = code.replace(/import { Responsive as ResponsiveGridLayout, WidthProvider } from 'react-grid-layout'/g, "import RGL, { WidthProvider } from 'react-grid-layout'")
code = code.replace(/const ResponsiveGridLayoutWithProvider = WidthProvider\(ResponsiveGridLayout\)/g, "const ResponsiveGridLayoutWithProvider = WidthProvider(RGL)")
fs.writeFileSync('frontend/src/App.tsx', code)
