const fs = require('fs')

let code = fs.readFileSync('frontend/src/App.tsx', 'utf-8')
code = code.replace(/<PanelHeader \n                    title=\{getPanelTitle\(panel.type\)\}\n                    onClose=\{panels\.length > 1 \? \(\) => handleClosePanel\(panel\.id\) : undefined\}\n                    onSplit=\{\(\) => handleSplit\(panel\.id\)\}\n                    onChangeType=\{\(type\) => handleChangeType\(panel\.id, type\)\}\n                  \/>/g, "<PanelHeader \n                    title={getPanelTitle(panel.type)}\n                    onClose={panels.length > 1 ? () => handleClosePanel(panel.id) : undefined}\n                    onSplit={() => handleSplit(panel.id)}\n                    onChangeType={(type) => handleChangeType(panel.id, type)}\n                    onExportMd={() => document.dispatchEvent(new CustomEvent(`export-md-${panel.id}`))}\n                    onExportPdf={() => document.dispatchEvent(new CustomEvent(`export-pdf-${panel.id}`))}\n                  />")
code = code.replace(/<Editor noteId=\{activeNoteId\} \/>/g, "<Editor noteId={activeNoteId} panelId={panel.id} />")
fs.writeFileSync('frontend/src/App.tsx', code)

let code2 = fs.readFileSync('frontend/src/components/Editor.tsx', 'utf-8')
code2 = code2.replace(/interface EditorProps \{\n  noteId: string \| null\n  inFocusMode\?: boolean\n\}/g, "interface EditorProps {\n  noteId: string | null\n  inFocusMode?: boolean\n  panelId?: string\n}")
code2 = code2.replace(/export default function Editor\(\{ noteId, inFocusMode = false \}: EditorProps\) \{/g, "export default function Editor({ noteId, inFocusMode = false, panelId }: EditorProps) {\n  useEffect(() => {\n    if (!panelId) return\n    const handleExportMd = () => _exportMD()\n    const handleExportPdf = () => _exportPDF()\n    document.addEventListener(`export-md-${panelId}`, handleExportMd)\n    document.addEventListener(`export-pdf-${panelId}`, handleExportPdf)\n    return () => {\n      document.removeEventListener(`export-md-${panelId}`, handleExportMd)\n      document.removeEventListener(`export-pdf-${panelId}`, handleExportPdf)\n    }\n  }, [panelId, content, title])")
fs.writeFileSync('frontend/src/components/Editor.tsx', code2)
