const fs = require('fs')
let code = fs.readFileSync('frontend/src/App.tsx', 'utf-8')
code = code.replace(/import \* as ReactGridLayoutModule from 'react-grid-layout\/index\.js'/g, "import { Responsive as ResponsiveGridLayout, WidthProvider } from 'react-grid-layout'")
code = code.replace(/import { Responsive as ResponsiveGridLayout } from 'react-grid-layout'\n/g, "")
code = code.replace(/const WidthProvider = \(ReactGridLayoutModule as any\)\.WidthProvider\n/g, "")
fs.writeFileSync('frontend/src/App.tsx', code)
