const fs = require('fs')

let code2 = fs.readFileSync('frontend/src/components/Editor.tsx', 'utf-8')

code2 = code2.replace(/\/\/ @ts-ignore\n  useEffect\(\(\) => \{\n    if \(\!panelId\) return\n    const handleExportMd = \(\) => _exportMD\(\)\n    const handleExportPdf = \(\) => _exportPDF\(\)\n    document.addEventListener\(`export-md-\$\{panelId\}`\, handleExportMd\)\n    document.addEventListener\(`export-pdf-\$\{panelId\}`\, handleExportPdf\)\n    return \(\) => \{\n      document.removeEventListener\(`export-md-\$\{panelId\}`\, handleExportMd\)\n      document.removeEventListener\(`export-pdf-\$\{panelId\}`\, handleExportPdf\)\n    \}\n  \}, \[panelId, content, title\]\)\n\n  const _exportPDF = async \(\) => \{/g, "const _exportPDF = async () => {")

code2 = code2.replace(/export default function Editor\(\{ noteId, inFocusMode = false, panelId \}: EditorProps\) \{/g, "export default function Editor({ noteId, inFocusMode = false, panelId }: EditorProps) {\n  useEffect(() => {\n    if (!panelId) return\n    const handleExportMd = () => document.getElementById(`export-md-btn-${panelId}`)?.click()\n    const handleExportPdf = () => document.getElementById(`export-pdf-btn-${panelId}`)?.click()\n    document.addEventListener(`export-md-${panelId}`, handleExportMd)\n    document.addEventListener(`export-pdf-${panelId}`, handleExportPdf)\n    return () => {\n      document.removeEventListener(`export-md-${panelId}`, handleExportMd)\n      document.removeEventListener(`export-pdf-${panelId}`, handleExportPdf)\n    }\n  }, [panelId])")

code2 = code2.replace(/\{\/\* Topbar: Only show in regular mode, not in focus mode \(handled by Layout\/MainView\) \*\/\}/g, "{/* Hidden buttons for external export trigger */}\n        <button id={`export-md-btn-${panelId}`} onClick={_exportMD} className=\"hidden\" />\n        <button id={`export-pdf-btn-${panelId}`} onClick={_exportPDF} className=\"hidden\" />\n        {/* Topbar: Only show in regular mode, not in focus mode (handled by Layout/MainView) */}")

code2 = code2.replace(/<button\n                onClick=\{toggleFocusMode\}/g, "<div className=\"relative\">\n            <button\n              onClick={() => setShowVersions(!_showVersions)}\n              className=\"px-3 py-1.5 text-xs bg-white/5 hover:bg-white/10 text-text-secondary rounded transition-colors\"\n              title=\"Histórico de Versões\"\n            >\n              ⏱️\n            </button>\n            {_showVersions && (\n              <div className=\"absolute right-0 mt-2 w-64 glass-panel border border-accent-primary/20 rounded-md shadow-xl py-2 z-50\">\n                <div className=\"px-3 pb-2 mb-2 border-b border-white/10 text-xs font-semibold text-accent-primary text-glow-neon\">\n                  Histórico de Versões\n                </div>\n                {_versions.length === 0 ? (\n                  <div className=\"px-3 text-xs text-text-muted\">Nenhum backup disponível.</div>\n                ) : (\n                  _versions.map((v) => (\n                    <div key={v.id} className=\"px-3 py-2 hover:bg-white/5 flex flex-col gap-1 transition-colors\">\n                      <span className=\"text-xs text-text-primary truncate\">{v.title}</span>\n                      <div className=\"flex justify-between items-center\">\n                        <span className=\"text-[10px] text-text-muted\">{new Date(v.created_at).toLocaleString()}</span>\n                        <button \n                          onClick={() => _handleRestore(v.id)}\n                          className=\"text-[10px] text-accent-primary hover:text-accent-glow\"\n                        >\n                          Restaurar\n                        </button>\n                      </div>\n                    </div>\n                  ))\n                )}\n              </div>\n            )}\n          </div>\n\n              <button\n                onClick={toggleFocusMode}")

fs.writeFileSync('frontend/src/components/Editor.tsx', code2)
